CREATE DATABASE IF NOT EXISTS `your_db_name`;

USE `your_db_name`;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	type VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS conferences (
	id INT AUTO_INCREMENT PRIMARY KEY,
	organizerId INT NOT NULL,
	name VARCHAR(255) NOT NULL UNIQUE,
	FOREIGN KEY (organizerId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS conference_reviewers (
	conferenceId INT NOT NULL,
	reviewerId INT NOT NULL,
	PRIMARY KEY (conferenceId, reviewerId),
	FOREIGN KEY (conferenceId) REFERENCES conferences(id) ON DELETE CASCADE,
	FOREIGN KEY (reviewerId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS articles (
	id INT AUTO_INCREMENT PRIMARY KEY,
	authorId INT NOT NULL,
	conferenceId INT NOT NULL,
	articleName VARCHAR(255) NOT NULL UNIQUE,
	status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
	reviewerOne INT NOT NULL,
	reviewerTwo INT NOT NULL,
	FOREIGN KEY (authorId) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (conferenceId) REFERENCES conferences(id) ON DELETE CASCADE,
	FOREIGN KEY (reviewerOne) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (reviewerTwo) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS article_feedbacks (
	id INT AUTO_INCREMENT PRIMARY KEY,
	articleId INT NOT NULL,
	authorId INT NOT NULL,
	feedback VARCHAR(255) NOT NULL,
	FOREIGN KEY (articleId) REFERENCES articles(id) ON DELETE CASCADE,
	FOREIGN KEY (authorId) REFERENCES users(id) ON DELETE CASCADE
);
